### ISSUE TITLE
ГДЕ ПЕРЕВОД, ЛЕБОВСКИ?

### ISSUE THREAD

**Issue by 778b** [starfort-station/station-14#10]
**Описание:**

Не переведены crate (их дохуя) в консоли заказа грузов.

**Пошаговая инструкция по воспроизведению:**

1. Открыть консоль.
2. Ахуеть от увиденного перевода.
3. Написать о базе.

**Скриншоты или видео:**

Бля, тебе сложно глянуть?

**Comment by MetalSage** [comment]
Закрой исуй, я перевёл

**Comment by kzhanik** [comment]
Локализируй нормально для начала
