### ISSUE TITLE
Добавить чистоботу и медиботу акцент дрона

### ISSUE THREAD

**Issue by Gerkada** [starfort-station/station-14#101]
Чистоботы и медиботы по непонятным мне причинам (спасибо, визарды) имеют компонент людской речи и это ХАРАМ. Нужно добавить им акцент дрона, что бы вместо нормальной речи они говорили "Бип.", "Буп." и прочее, ибо всякие ЛРП товарищи считают своим долгом орать на них маты капсом.

**Comment by kzhanik** [comment]
Шутки про харам...

**Comment by 778b** [comment]
эти боты не разумные по идеи, у них есть только заложенные фразы, то есть это супер примитив

**Comment by kzhanik** [comment]
Чистоботу я могу спокойно дать акцент дрона, однако с медиботом возникает дилемма, так как во время лечения медибот просит пациентов не двигаться. Если дашь акцент - он начнёт херню пациентам говорить, поэтому я решил не использовать акцент для медибота в данном случае.
