### ISSUE TITLE
Ксенослизь.

### ISSUE THREAD

**Issue by 778b** [starfort-station/station-14#111]
**Краткое описание:**
Тоже самое что паутина только у ксено к ней иммунитет, и выглядит как слизь, можете просто паутину покрасить.

**Comment by kzhanik** [comment]
А что за слизь? Зачем она? Что она должна делать?

**Comment by MetalSage** [comment]
> А что за слизь? Зачем она? Что она должна делать? 

Замедлять как паутина

**Comment by kzhanik** [comment]
Визарды добавили клей как жидкость.

**Comment by 778b** [comment]
спрайты расположены по пути Resources/Textures/Starfort/Objects/Misc/xenomucilage.rsi
