### ISSUE TITLE
Добавить грудолома

### ISSUE THREAD

**Issue by 778b** [starfort-station/station-14#112]
**Краткое описание:**
Добавить в игру прототип грудолома, вместо спрайта пока можно использовать спрайт цыпленка.
грудолом не может бить, пока он ничего не может, просто цыпленок, но из фракции ксено.
Resources\Textures\Mobs\Animals\chick.rsi
фото грудолома:
![image](https://user-images.githubusercontent.com/33431126/235107203-32015903-c36e-4c46-b44d-5a8b54f7e2ca.png)

**Comment by kzhanik** [comment]
Окей, гляну что могу сделать
