### ISSUE TITLE
Дать право использования команды adminwho всем игрокам.

### ISSUE THREAD

**Issue by kzhanik** [starfort-station/station-14#119]
**Краткое описание:**

Дать право использования команды adminwho всем игрокам.

**Полное описание:**

Дать право использования команды adminwho всем игрокам.

**Почему это нужно добавить в игру:**
Чтобы жити краще

**Comment by 778b** [comment]
чтобы набегаторы знали сколько админов и есть ли они вообще? Чтобы могли заробастить весь сервер, заруинить катку даммом? План говно

**Comment by 778b** [comment]
если он насрет в ахелп то ему очевидно напишет что ваше сообщение отправлено в дискорд, и для меня это звоночек, если игрок в ахелп насрал без причины, значит он пойдет пакостить со 100% вероятностью

**Comment by 778b** [comment]
и да, ему не напишет что админов нет 
![image](https://user-images.githubusercontent.com/33431126/235529892-c5ffcdfa-7aca-4fdb-9f28-ebc9527bb3a7.png)

**Comment by kzhanik** [comment]
> если он насрет в ахелп то ему очевидно напишет что ваше сообщение отправлено в дискорд, и для меня это звоночек, если игрок в ахелп насрал без причины, значит он пойдет пакостить со 100% вероятностью

Игрок может написать что-то умное по типу: "админы помогите, а как ходить" .

**Comment by kzhanik** [comment]
> и да, ему не напишет что админов нет 
> ![image](https://user-images.githubusercontent.com/33431126/235529892-c5ffcdfa-7aca-4fdb-9f28-ebc9527bb3a7.png)
> 

Ваше сообщение было передано администраторам в Discord

**Comment by 778b** [comment]
> > и да, ему не напишет что админов нет
> > ![image](https://user-images.githubusercontent.com/33431126/235529892-c5ffcdfa-7aca-4fdb-9f28-ebc9527bb3a7.png)
> 
> Ваше сообщение было передано администраторам в Discord

дак эта хуйня пишется внезависимости от того - есть админы или нет

> > если он насрет в ахелп то ему очевидно напишет что ваше сообщение отправлено в дискорд, и для меня это звоночек, если игрок в ахелп насрал без причины, значит он пойдет пакостить со 100% вероятностью
> 
> Игрок может написать что-то умное по типу: "админы помогите, а как ходить" .

не все такие умные, да и очевидные вопросы мало кто будет такие задавать, вопрос только в том НАХУЯ ДАВАТЬ самоантагам ЕЩЕ ОДИН РЫЧАГ, понижать порог самоантагов? чтобы они не просто высирали в ахелп что-то умное и думали есть ли админы или нет, а просто вводили команду? - гениально

**Comment by 778b** [comment]
да и хуйни про которую ты говорил "Для того чтобы набегатору понять, есть ли админы на сервере, то ему достаточно насрать "я ебал тебя в рот" (ну или что-то более цивильное) в ахелп", оказывается не работает, мой скриншот был в доказательство к этому

**Comment by kzhanik** [comment]
Ок, а если адмем решил нащитспавнить?

**Comment by 778b** [comment]
> Ок, а если адмем решил нащитспавнить?

то как это поможет обычным игрокам? Если они захотят написать на него жалобу, то это будет тоже самое как раньше писали жалобы на админов и указывали раунд, а уже другие админы приходят и смотрят логи какой админ был онлайн, а если несколько админов то они полюбому знают кто насрал
