### ISSUE TITLE
Пофиксить шлемы дедов и киберсана (+ инструкция)

### ISSUE THREAD

**Issue by 778b** [starfort-station/station-14#123]
**Описание:**
На ошибке сказано что шлем деда и киберсана не указаны в мете, надо указать отсутствующие поля
![image](https://user-images.githubusercontent.com/33431126/235869594-f21bc77e-9873-4756-b2a4-9964dcf9d22c.png)

**Comment by kzhanik** [comment]
Это визарды бан допустили?

**Comment by 778b** [comment]
нет
