### ISSUE TITLE
Отвалился бот с логами раундов

### ISSUE THREAD

**Issue by Gerkada** [starfort-station/station-14#13]
**Описание:**
После того как мы перешли на новый девственно чистый билд отвалился бот, который логировал начало и номер нового раунда. Нехорошо, нужно его вернуть.

**Comment by 778b** [comment]
Это kikimojar должен пофиксить

**Comment by Gerkada** [comment]
> Это kikimojar должен пофиксить

Ну окей, написал ему в ТГ
