### ISSUE TITLE
Ребаланс ксено

### ISSUE THREAD

**Issue by 778b** [starfort-station/station-14#168]
**Краткое описание:**
Наших ксено, которые находятся Resources/Prototypes/Starfort/Entities/Mobs/xeno.yml
надо добавить невосприимчивость к вспышкам и сократить кол-во ХП до 65-70% от текущего

**Comment by kzhanik** [comment]
Беру на себя

**Comment by kzhanik** [comment]
Кстати молодец что указал путь, иначе мне бы пришлось ебашить в поисках Немо 3

**Comment by kzhanik** [comment]
Запрос выполнен.
