### ISSUE TITLE
Полевой инженер получает не тот комбез

### ISSUE THREAD

**Issue by kzhanik** [starfort-station/station-14#175]
**Описание:**

В шкафу полевого инженера лежит комбез полевого врача.

**Пошаговая инструкция по воспроизведению:**
Открыть шкаф полевого инженера

**Скриншоты или видео:**

**Comment by 778b** [comment]
я пофикшу, у меня как раз тут с вешами ПР готовится

**Comment by 778b** [comment]
closed in #27
