### ISSUE TITLE
Вещмешок экспедиторов обделили по вместимости

### ISSUE THREAD

**Issue by kzhanik** [starfort-station/station-14#177]
**Описание:**

Вещмешок экспедиторов имеет 100 вместимости вместо 120

**Comment by Gerkada** [comment]
> **Описание:**
> 
> Вещмешок экспедиторов имеет 100 вместимости вместо 120

Так у него и замедление куда меньше

**Comment by kzhanik** [comment]
> Так у него и замедление куда меньше

Так вещмешок это на то и вещмешок, что он более вместительный. Все вещмешки имеют вместимость в 120.
