### ISSUE TITLE
Сделать карту с заброшенной станцией

### ISSUE THREAD

**Issue by 778b** [starfort-station/station-14#23]
**Краткое описание:**
Создание большой заброшенной станции которую заселили ксеносы (использовать спавнеры).
ТЗ: делать как угодно и что угодно, можно наделать разгермов, разбросать трупов, скелетов, их экипировку, разлить жидкостей разных, накидать газов, сделать вид что эту станцию не посещали уже очень очень давно, все остальное на ваше усмотрение.
Закинуть в \Resources\Maps\Expedition.

Слова которые приходят мне в голову: заброшенная шахтерская станция, станция газодобычи, космический корабль который потерпел крушение, исследовательская станция на астероиде.

Дополнительные баллы:
- наличие органов разбросанных по станции
- гильзы
- трупы
- отсутствие света
- экстренное освещение

**Comment by MetalSage** [comment]
Попытаюсь сделать 👍🏿
