### ISSUE TITLE
Шаттл прибытия не увозит на станцию

### ISSUE THREAD

**Issue by Gerkada** [starfort-station/station-14#44]
**Описание:**
Когда ты пытаешься в терминале сесть на шаттл прибытия, то он улетает без тебя, а тебя ТПшит обратно в терминал. Без помощи админов терминал покинуть невозможно.
**Пошаговая инструкция по воспроизведению:**
1.Зайти на сервер
2.Очутится на терминале 
3. Попытаться улететь на шаттле
4. Понять, что ты в ловушке

**Comment by kzhanik** [comment]
Я вот сейчас в агосте слежу за игроками и не могу увидеть что этот баг есть. Может они ранее летали в раунде на шаттле терминала?

**Comment by Gerkada** [comment]
> Я вот сейчас в агосте слежу за игроками и не могу увидеть что этот баг есть. Может они ранее летали в раунде на шаттле терминала?

Спроси у Даки Джула и Антона Чехова в Ахелпе, они подтвердят, что баг есть. Я лично Чехову (Karlint) открывал портал с терминала на станцию, ибо шаттл не забирал его.

**Comment by kzhanik** [comment]
А респу может давали?

**Comment by Gerkada** [comment]
> А респу может давали?

Нет.

**Comment by kzhanik** [comment]
Не могу повторить баг, кажется вас обманули.
