### ISSUE TITLE
Боевой медипен

### ISSUE THREAD

**Issue by 778b** [starfort-station/station-14#66]
**Краткое описание:**
Добавить прототип боевого медипена по адрессу Resources\Prototypes\Entities\Objects\Specific\Medical\hypospray.yml
Максимальная емкость 18 (у экстренного 15)
Состав: 
+ Бикаридин 9
+ Транексамовая кислота 3
+ Дексалин плюс 6

**Comment by fedKotikeD** [comment]
Я возьмусь
