### ISSUE TITLE
Добавить роль новобранца

### ISSUE THREAD

**Issue by 778b** [starfort-station/station-14#78]
**Краткое описание:**
Солдат на минималках, нету сб доступа.
Добавить ему шкафчик, прототип роли, тайм трекер и спавнер.

**Comment by fedKotikeD** [comment]
Думаю возьмусь за это после того, как доделаю командира отряда

**Comment by 778b** [comment]
> Думаю возьмусь за это после того, как доделаю командира отряда

Доделай сначала, командир и радио ксено уже за тобой висит

**Comment by fedKotikeD** [comment]
> > Думаю возьмусь за это после того, как доделаю командира отряда
> 
> Доделай сначала, командир и радио ксено уже за тобой висит

Помню, помню. При первой возможности захожу в комп и прогаю

**Comment by kzhanik** [comment]
Новобранца же сделали?

**Comment by 778b** [comment]
closed in #128
