### ISSUE TITLE
Проставить копирайты (изменить текст комментариев)

### ISSUE THREAD

**Issue by 778b** [starfort-station/station-14#8]
*Краткое описание:**
Мы добавили довольно много спрайтов, надо им всем проставить наш копирайт, то есть во всех файлах meta.js с нашими спрайтами выставить "copyright: starfort-station-14"

пример того что надо исправить
![image](https://user-images.githubusercontent.com/33431126/231155916-93c632c6-2198-4ec9-9d7f-655b0086dd39.png)

**Comment by fedKotikeD** [comment]
сделаю

**Comment by kzhanik** [comment]
> сделаю

Где?
